### ISSUE TITLE
Surface Pro 4: Touching the screen while using the pen causes freeze

### ISSUE THREAD

**Issue by kanzwataru** [jakeday/linux-surface#107]
If the screen is touched while using the pen, both pen and touch stop working for a few seconds. The expected behaviour is for the pen to continue to work while the touch is ignored. It's a bit difficult to explain so I've also made a video:

[https://www.youtube.com/watch?v=c1u7kxP-k_w](https://www.youtube.com/watch?v=c1u7kxP-k_w)

In the video I've demonstrated by keeping my right hand off the screen and touching it with my left hand, in order to make it easier to see. While drawing it is natural to rest the hand on the screen so this issue comes up constantly. I am using Ubuntu Gnome 16.04 LTS with your 4.15.8-1 kernel. The program used to draw was Krita although this happens in any program.

**Comment by jakeday** [comment]
@kanzwataru Can you get me the output of dmesg after this happens?

**Comment by kanzwataru** [comment]
It seems my pen's battery has gone flat, I'll have to get back to you in a few days. Are you able to reproduce it on your hardware?

**Comment by jakeday** [comment]
@kanzwataru No, I'm not able to reproduce it.

**Comment by kanzwataru** [comment]
@jakeday 
Popped in a new battery, here is the dmesg output right after triggering the freeze. Hopefully this helps!

[surface-4-pen-freeze.txt](https://github.com/jakeday/linux-surface/files/1825453/surface-4-pen-freeze.txt)

**Comment by jakeday** [comment]
@kanzwataru Can you test with the latest build I pushed up?

**Comment by kanzwataru** [comment]
@jakeday Unfortunately this doesn't fix it. I tried both 4.14.29 and 4.15.12. Could it be that it's because I'm using 16.04LTS? Here are the dmesg dumps for both kernel versions:

[surface-4.15.12.txt](https://github.com/jakeday/linux-surface/files/1845659/surface-4.15.12.txt)
[surface-4.14.29.txt](https://github.com/jakeday/linux-surface/files/1845660/surface-4.14.29.txt)

**Comment by jakeday** [comment]
@kanzwataru I still cannot reproduce.

Is anyone else experiencing this issue?

**Comment by kanzwataru** [comment]
I can try with a different/newer distro. Would that have anything to do with it?

**Comment by jakeday** [comment]
Give it a shot! It most definitely could!

**Comment by kanzwataru** [comment]
Out of curiousity, which distro are you using?

**Comment by jakeday** [comment]
The latest kde neon.

**Comment by kanzwataru** [comment]
Alright, so I've done some more testing and it turns out to be... a GNOME issue! More specifically, a GNOME 3.16 issue. GNOME on Ubuntu 17.10 works fine, as does OpenBox (and presumably other WMs/DEs) on 16.04LTS. Sorry for wasting your time, wasn't an issue with your kernel patches after all. Thanks for the awesome hardware support!

**Comment by jakeday** [comment]
Thanks for updating us!
