### ISSUE TITLE
Surface Book: Touch and pen stop working after a time on 4.16.x

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#171]
I am running 4.16.7 on Debian Stable on Surface Book, and touch randomly stopped working.

I'm attaching dmesg log. The thing is, the loss of touch input happened several minutes AFTER the last entry in the dmesg log: [dmesg.txt](https://github.com/jakeday/linux-surface/files/1980778/dmesg.txt)

I ran the following commands

rmmod intel_ipts
rmmod mei_me
rmmod mei

#load ipts modules
modprobe intel_ipts
modprobe mei_me
modprobe mei

and touch was fixed. These additional entries were added to the dmesg when reloading the modules:
```

[33711.491208] IPTS ipts_mei_cl_exit() is called
[33711.690787] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error in reading m2h msg
[33711.690842] IPTS removed
[33711.777868] IPTS ipts_mei_cl_init() is called
[33711.786913] probing Intel Precise Touch & Stylus
[33711.786914] IPTS using DMA_BIT_MASK(64)
[33711.795068] input: ipts 1B96:005E UNKNOWN as /devices/pci0000:00/0000:00:16.4/mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F/0044:1B96:005E.000B/input/input175
[33711.795192] input: ipts 1B96:005E Pen as /devices/pci0000:00/0000:00:16.4/mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F/0044:1B96:005E.000B/input/input186
[33711.795254] input: ipts 1B96:005E Touchscreen as /devices/pci0000:00/0000:00:16.4/mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F/0044:1B96:005E.000B/input/input187
[33711.795311] input: ipts 1B96:005E Mouse as /devices/pci0000:00/0000:00:16.4/mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F/0044:1B96:005E.000B/input/input188
[33711.795382] hid-multitouch 0044:1B96:005E.000B: input,hidraw1: <UNKNOWN> HID v13500.00 Mouse [ipts 1B96:005E] on heci3
[33712.060542] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: touch enabled 4

```

Not sure how related is this to this: https://github.com/jakeday/linux-surface/issues/164 but seems very similar.

**Comment by GammaPi** [comment]
Yes those command works for Surface Pro 4 too~

**Comment by kitakar5525** [comment]
- kernel 4.17.3 on SB1

I noticed that merely turning the display off can also fix this issue.

```bash
# turn the display off then on
xset dpms force off && xset dpms force on
```

dmesg after turning display off and then turning on:
```bash
# Nothing was written on dmesg between touch stop and turning the display off.
[70454.323559] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: 0x80000004 failed status = 14
[70455.177397] [drm] Reducing the compressed framebuffer size. This may lead to less power savings than a non-reduced-size. Try to increase stolen memory size if available in BIOS.
[70455.186172] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: touch enabled 4
```

**Comment by yuzvir** [comment]
Confirm this on Surface Pro 4 with Fedora 28 and kernel version 4.17.10

**Comment by condemnedmeat** [comment]
I'm using 4.17.3 & Ubuntu 16.04.5
It happens very, very often for me.

I notice it tends to happen when I select "Search your computer" or often using Opera browser or when I click on the status icon for the on-screen keyboard. It's like the graphics are crashing touch.

Thank you for working on this. Would you (jakeday) suggest I use 18.04 over 16 for best results using your kernal?

**Comment by tmarkov** [comment]
Another note: Sometimes, I lose touch input after waking up from hibernate (or suspend). In those cases, restarting the modules doesn't help.

**Comment by jakeday** [comment]
Fixed in 4.18.7 release.

**Comment by xaviervilla** [comment]
I'm running 4.18.7 on Surface Book 1 and issue persists unfortunately. When I run `xset dpms force off && xset dpms force on` like @kitakar5525 suggested, it does actually re-enable the touch (Thank you for the tip). I think that for now I'll just set that as a custom keyboard shortcut as a workaround since I don't use touch all that often.
