### ISSUE TITLE
Error on config.patch for kernel compile - "can't find file to patch at input line 3"

### ISSUE THREAD

**Issue by battaglia01** [jakeday/linux-surface#189]
When compiling the kernel, the instructions in say

> 5. Get current config file and patch it:
```
cat /boot/config-$(uname -r) > .config
patch -p1 < ~/linux-surface/patches/config.patch
```
Upon doing this step, I get the following error:

```
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- config-stock	2018-04-30 19:19:53.667563564 -0400
|+++ config-surface	2018-04-30 19:22:03.105721430 -0400
--------------------------
File to patch: 
```

For reference, the first five lines of `config.patch` are

```
--- config-stock	2018-04-30 19:19:53.667563564 -0400
+++ config-surface	2018-04-30 19:22:03.105721430 -0400
@@ -52,7 +52,7 @@
 CONFIG_INIT_ENV_ARG_LIMIT=32
 CONFIG_CROSS_COMPILE=""
...
```

What could be causing this? Should there be a file called "config-stock" somewhere?

**Comment by georgetzimas** [comment]
Just wanted to report that I ran into the exact same issue when trying to patch the kernel yesterday.

Dual booting a Surface Pro 4 with W10 and Fedora 28, attempting to patch kernel 4.16.13.

Let me know if I can provide any more information to help solve this.

**Comment by battaglia01** [comment]
It seems to build correctly on Arch here, using this repo posted on reddit:

https://www.reddit.com/r/SurfaceLinux/comments/8j5ifc/for_those_of_you_who_want_to_run_arch_linux_i/

This is basically a script that takes this repo and automates the process of building it. Perhaps we could poke in there to find how they deal with this config-stock issue.

**Comment by georgetzimas** [comment]
@battaglia01 Thanks for pointing me to that script. I had installed Fedora because I'd heard it had good out of the box support for the Surface Pro. I went back to my preferred distro Manjaro and using that script and instructions I was able to patch, compile and install the kernel. One additional thing I had to do was copy and paste across the drivers for IPTS and now touchscreen works too.

**Comment by battaglia01** [comment]
No problem. It looks like the way they do this is they put the entire config file in the repo, rather than using a patch: https://github.com/dmhacker/arch-linux-surface/blob/master/base/configs/config.4.16

I wonder, is there some way we could extrapolate from what they're doing and merge into this repo? I'm using an Ubuntu-based distro (Neon) and would prefer to not switch back to Manjaro.

I wonder if @jakeday has any thoughts?

**Comment by jakeday** [comment]
This has been fixed. It was an issue with the names of the config files in the patch.

**Comment by battaglia01** [comment]
The new config.patch names still don't work for me. I now get the following error:

```
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/config	2018-04-30 19:19:53.667563564 -0400
|+++ b/config	2018-04-30 19:22:03.105721430 -0400
--------------------------
File to patch: 
```

What file is this supposed to be patching?

**Comment by battaglia01** [comment]
@jakeday figured it out, there are two things. The first is the files should instead be

```
--------------------------
|--- a/.config	2018-04-30 19:19:53.667563564 -0400
|+++ b/.config	2018-04-30 19:22:03.105721430 -0400
--------------------------
```

Yours are listed just as "config" and not ".config".

If you run this, you then (typically) get the following error:
```
patching file .config
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

This is because the install instructions say as follows:
```
cat /boot/config-$(uname -r) > .config
patch -p1 < ~/linux-surface/patches/config.patch
```

The main problem is that it just copies the current config file from /boot/, but if that config file doesn't match your original reference, patch won't work.

The best way to do this would be to make it patch from the .config file that's already present in the linux-stable repo. However, running patch on there I get the same error. What version config am I supposed to be using as a reference? I did all of this on the 4.16.7 kernel.

**Comment by jakeday** [comment]
Fixed it. Sorry!
