### ISSUE TITLE
Touchscreen (irrecoverably) lost after suspend/hibernate

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#270]
After suspend or hibernate, I sometimes lose touchscreen functionality (not always). It also could happen after other things that cause it to get disconnected, such as
```
echo 1 > /sys/bus/pci/devices/0000:00:16.4/remove
echo 1 > /sys/bus/pci/rescan
```

IPTS gets stuck into state 1:
```
root@todor-surface:/sys/kernel/debug/ipts# cat status 
sensor mode : 1
ipts state : 1
```

And touchscreen is not listed in xinput:
root@todor-surface:/sys/kernel/debug/ipts# xinput
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Mouse        	id=9	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Consumer Control	id=10	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Touchpad     	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Surface Pro 3/4 Buttons                 	id=7	[slave  keyboard (3)]
    ↳ Microsoft Surface Keyboard Keyboard     	id=8	[slave  keyboard (3)]
    ↳ Microsoft Surface Keyboard Consumer Control	id=16	[slave  keyboard (3)]
```

I haven't found anything that can restore touch input. Reloading the modules intel_ipts, mei_me and mei doesn't help. I've tried unloading the modules, removing 0000:00:16.4 and 0000:00:16.0, rescanning and then reloading the modules, but no luck.

Also, I've mentioned this in https://github.com/jakeday/linux-surface/issues/242, but it's ultimately a separate issue, so it makes sense to have it separately.

One interesting observation is that time matters. If I suspend for a mew seconds, I very rarely lose touch. On the other hand, if I suspend for 10 minutes or longer, it happens quite often. I haven't done as extensive testing with hibernate, since it's rarer there and slower to test.

I've attached dmesg (after suspend): [dmesg.txt](https://github.com/jakeday/linux-surface/files/2457613/dmesg.txt). Note, this happens with the newest kernel too. My dmesg is from older one, because 4.17 and 4.18 come with too many regression on my device to be worth the upgrade.

**Comment by mirh** [comment]
> error in reading m2h msg

That seems some clue

**Comment by mirh** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=04cb3ae895d7efdc60f0fe17182b200a3da20f09 
Could this have anything to do with it?

**Comment by tmarkov** [comment]
Not really, that's a new patch, while this isn't a new issue. I'd even say (though I'm not sure) it's most likely inherited from the 4.9 IPTS code.

I don't think the m2h msg error is related either; it seems to appear when I reload the IPTS modules.

**Comment by battaglia01** [comment]
Same problem here.

**Comment by battaglia01** [comment]
FYI, noticed you mentioned the problem above with 4.16 - have the same issue on 4.17 on SP4. I haven't upgraded to 4.18 yet since I saw some other regressions (caps lock light stuck, etc). May be fixed in the newest 4.18, not sure.

**Comment by mirh** [comment]
You could try to bisect with the binary releases here on github

**Comment by jonas2515** [comment]
Hmm, are you guys totally sure this was not a problem with 4.16? We could bisect the commit.

For me sometimes touch is lost after suspend, and a few minutes later the gpu completely locks up...

**Comment by tmarkov** [comment]
@jonas2515 You must have misread something...

This has been a problem with 4.14, 4.15, 4.16, 4.17 and 4.18. I suspect it goes all the way to the original code in 4.9, but since I never could get suspend to work in 4.9, I couldn't check.

**Comment by jonas2515** [comment]
@tmarkov Okay, in the other threads it always sounded like everything worked in 4.16. I only have my Pro 2017 for a week now and I'm still catching up with all the linux bugs it has :)

The more I look at those issues, the more I think there's something shady going on with our PCI interrupt handling. Guess what the error is that kills the ipts driver? `14 Operation timed out`, that's the same thing we're seeing with the wifi chip.

**Comment by jonas2515** [comment]
Btw: There's a bug in gnome that breaks touch input after suspending by lid-close: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/113

If you only suspend using the power button or systemctl it gets a lot better :)

**Comment by battaglia01** [comment]
I am able to create the issue by typing the following commands:

```
sudo modprobe -r intel_ipts
sudo modprobe -r mei_me
sudo modprobe -r mei
```

This causes touch to drop. Then, if I put the modules back in, as follows:

```
sudo modprobe mei
sudo modprobe mei_me
sudo modprobe intel_ipts
```

then touch remains cut regardless. I've had this problem with 4.16, 4.17, 4.18 on SP4 running Kubuntu and KDE Neon.

**Comment by jakeday** [comment]
This is due to a timing for loading the clients after a reset/power cycle. I'm handling this in the upcoming 4.20 kernel.

**Comment by jakeday** [comment]
Can someone please test this with the 4.19.19-1 release? You'll need to run the setup.sh script again.

**Comment by mjakl** [comment]
I tried the kernel using the Arch repo (updated recently) and I ran the setup.sh.

I'm running a SB2 15'' and Hibernate is only able to resume into X when I disable the Touchscreen (still). Resume works in principle (to the console), but X is broken. I haven't played with removing and installing the modules after resume, though.

Though, I'm getting new errors on startup:

```
[    2.343003] ------------[ cut here ]------------
[    2.343005] Attribute disable_auto_ds: Invalid permissions 01
[    2.343024] WARNING: CPU: 1 PID: 242 at fs/sysfs/group.c:60 internal_create_group+0x303/0x380
[    2.343025] Modules linked in: mwifiex(+) kvm 8250_dw(+) i2c_algo_bit snd_hda_intel cec ipu3_cio2 snd_hda_codec v4l2_fwnode videobuf2_dma_sg videobuf2_memops iTCO_wdt rc_core iTCO_vendor_support irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel drm_kms_helper videobuf2_v4l2 snd_hda_core pcbc tpm_crb cfg80211 snd_hwdep videobuf2_common drm snd_pcm aesni_intel videodev snd_timer aes_x86_64 crypto_simd cryptd glue_helper rfkill intel_cstate mei_me snd intel_gtt intel_uncore agpgart evdev intel_rapl_perf syscopyarea sysfillrect sysimgblt fb_sys_fops mei soundcore media i2c_i801 idma64 intel_ish_ipc(+) pcspkr intel_ishtp intel_lpss_pci intel_lpss processor_thermal_device intel_pch_thermal intel_soc_dts_iosf tpm_tis tpm_tis_core tpm surface_acpi rng_core pinctrl_sunrisepoint rtc_cmos pinctrl_intel
[    2.343059]  int3400_thermal acpi_thermal_rel surfacepro3_button int3403_thermal hid soc_button_array dptf_power int340x_thermal_zone ac pcc_cpufreq crypto_user ip_tables x_tables ext4 crc32c_generic crc16 mbcache jbd2 fscrypto xhci_pci xhci_hcd crc32c_intel usbcore usb_common
[    2.343073] CPU: 1 PID: 242 Comm: systemd-udevd Not tainted 4.19.19-1-surface #1
[    2.343074] Hardware name: Microsoft Corporation Surface Book 2/Surface Book 2, BIOS 389.2370.769 10/02/2018
[    2.343076] RIP: 0010:internal_create_group+0x303/0x380
[    2.343078] Code: 89 4c 24 0c e8 58 0f d9 ff 0f 0b 49 8b 37 8b 4c 24 0c e9 4d ff ff ff 48 8b 36 48 c7 c7 20 7b e7 b8 89 4c 24 0c e8 37 0f d9 ff <0f> 0b 4b 8b 34 f7 8b 4c 24 0c e9 03 fe ff ff 4c 8b 65 30 e9 92 fd
[    2.343080] RSP: 0018:ffffa6b0c1fa7ce0 EFLAGS: 00010282
[    2.343081] RAX: 0000000000000000 RBX: ffff8ed5993f5c08 RCX: 0000000000000000
[    2.343083] RDX: 0000000000000007 RSI: ffffffffb8e6606e RDI: 00000000ffffffff
[    2.343084] RBP: ffffffffc0ea3390 R08: 0000000000000000 R09: 0000000000021480
[    2.343085] R10: 0000000463947180 R11: 0000000000011934 R12: ffff8ed59214ddd0
[    2.343086] R13: 0000000000000000 R14: 0000000000000002 R15: ffff8ed5930e1340
[    2.343088] FS:  00007fe480709cc0(0000) GS:ffff8ed59f240000(0000) knlGS:0000000000000000
[    2.343089] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.343090] CR2: 00005607fa4e6000 CR3: 00000004590a8005 CR4: 00000000003606e0
[    2.343091] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    2.343092] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    2.343093] Call Trace:
[    2.343100]  module_param_sysfs_setup+0x6d/0xd0
[    2.343103]  load_module+0x1fce/0x25f0
[    2.343106]  ? alloc_vmap_area+0x268/0x350
[    2.343111]  ? __se_sys_init_module+0x10a/0x170
[    2.343113]  __se_sys_init_module+0x10a/0x170
[    2.343118]  do_syscall_64+0x5b/0x170
[    2.343122]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[    2.343124] RIP: 0033:0x7fe48218756e
[    2.343126] Code: 48 8b 0d f5 18 0c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 49 89 ca b8 af 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d c2 18 0c 00 f7 d8 64 89 01 48
[    2.343127] RSP: 002b:00007fffacafea18 EFLAGS: 00000246 ORIG_RAX: 00000000000000af
[    2.343129] RAX: ffffffffffffffda RBX: 00005607f9a915b0 RCX: 00007fe48218756e
[    2.343130] RDX: 00007fe481bffecd RSI: 000000000009cec0 RDI: 00005607fa466cb0
[    2.343131] RBP: 00007fe481bffecd R08: 0000000000000004 R09: 0000000000000003
[    2.343132] R10: 00005607f9a78010 R11: 0000000000000246 R12: 00005607fa466cb0
[    2.343133] R13: 00005607f9a90d50 R14: 0000000000020000 R15: 00005607f9a915b0
[    2.343136] ---[ end trace 02e7d2bc8f3b77bf ]---
```

I'm not sure whether that's related to this issue.

Hope that helps somehow?

**Comment by tmarkov** [comment]
I did a bunch of power cycles (pci remove/rescan), and some suspend/resumes, and it seems the issue is resolved :). I'd wait a few more days to be sure, as in the past I couldn't reproduce it very reliably, but I'm very optimistic.

**Comment by jakeday** [comment]
This is resolved in 4.19.20-1 based on feedback received.

**Comment by korakios** [comment]
It’s still happening in my SP4 on
4.19.23-surface-linux-surface-1
4.19.27-surface-linux-surface-2
5.0.1-surface-linux-surface  4

[ 6823.436509] IPTS ipts_mei_cl_exit() is called
[ 6823.436624] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error in reading m2h msg
[ 6823.436710] IPTS removed
[ 6835.143692] IPTS ipts_mei_cl_init() is called
[ 6835.156343] probing Intel Precise Touch & Stylus
[ 6835.156345] IPTS using DMA_BIT_MASK(64)

It happens on suspend . Hibernate and resume works .

**Comment by realSpok** [comment]
I'm also still facing the same issue. On suspend + resume, IPTS has irrevocably crashed. 
I have tried reloading the modules, but to no avail. Doing this usually fix the problem in #374 ,that I also encounter, but not here.
I am also running kernel 5.0.1, and my dmesg shows the same output as korakios.

**Comment by NitroBAY** [comment]
Same goes for me 5.0.1 SB arch linux, modprobe doesn't help. It does not always do it but when  it does it never works again until restart.
