### ISSUE TITLE
Surface Pro 4: Multi-touch Input Stops Working Until Screen Rotate

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#31]
I found a sure-fire way to get the multitouch input to stop working.

0. make sure you're in multitouch mode (as root "echo 1 > /sys/kernel/debug/ipts/mode")
1. open chrome
2. open google maps
3. move the map around (with even just a single finger, no need to pinch and zoom)
4. see that no touch input (single or multi) works after a little bit of fussing around

To get touch input to work again rotate the screen.

**Comment by jakeday** [comment]
@thekswenson What device and ipts firmware are you using?

**Comment by legierski** [comment]
@jakeday Same issue here. SP4 and ipts_firmware_v78 as per readme.

**Comment by thekswenson** [comment]
SP4 with firmware v78

Kms

**Comment by jakeday** [comment]
@thekswenson @legierski Did you try the other firmware versions?

**Comment by jakeday** [comment]
Also, I can't seem to duplicate this on my Surface Book. Can you provide some logs?

**Comment by jakeday** [comment]
Figured it out. This is fixed in my next build, which is the new 4.14.0 build (yay for no more rc!)

**Comment by thekswenson** [comment]
With the 4.14.0 kernel I still have this issue, although I have to scroll and zoom a lot more until multitouch stops working.

I'm using the v78 firmware.   Multitouch doesn't work with the v76 firmware.  Is it worth trying the v79?

**Comment by jakeday** [comment]
@thekswenson Look at the README.md and use the correct firmware version for your device.

**Comment by thekswenson** [comment]
I'm using the correct firmware version:  v78 for SP4
The bug persists.

**Comment by legierski** [comment]
Again, the same issue on my SP4 on v78.

**Comment by jakeday** [comment]
If that's the case, I'll re-open the issue and look into it again.

**Comment by jakeday** [comment]
This should be fixed in my next update I'll be rolling out this weekend.

**Comment by jakeday** [comment]
Fixed in latest push.

**Comment by legierski** [comment]
I'm afraid I'm still experiencing the same issue, zooming in and out of google maps, in less than a minute.

**Comment by thekswenson** [comment]
It takes me a lot longer (with google maps) now, but it can still happen.
You folks know a way to reinstate touch without rotate?  Rotate doesn't always solve the problem for me, when rotate works.

**Comment by jakeday** [comment]
@thekswenson I just made some changes and re-built my 4.14.4 kernel. Can you give it a try and see if it fixes it for you?

**Comment by thekswenson** [comment]
@jakeday The 4.14.5 kernel still has problems...  I'll use the 4.14.4 kernel for a while and report back.

**Comment by thekswenson** [comment]
I experience the problem in 4.14.4 as well.   The "google maps" test does not pass (touch input drops out when zooming/scrolling on maps for a while).

**Comment by fridgecow** [comment]
I also experience this problem - probably good to mention it also affects the pen. It only seems to break when using touch (regardless of pen), and Chrome makes the issue worse - although it happens occasionally even without chrome.

**Comment by sebanc** [comment]
A workaround seems to be the use of lower resolutions.
Here is the xorg conf I currently use which makes 2 lower resolutions available and the touchscreen seems to work correctly with both:

`Section "Device"
   Identifier  "Intel Graphics"
EndSection
Section "Monitor"
   Identifier  "eDP1"
   Modeline    "2056x1368"  187.00  2056 2104 2136 2216  1368 1371 1381 1407 -hsync -vsync
   Modeline    "1368x912"    85.75  1368 1416 1448 1528   912  915  925  938 -hsync -vsync
EndSection
Section "Screen"
   Identifier  "Screen 0"
   Device      "Intel Graphics"
   Monitor     "eDP1"
EndSection`

Not sure about the origin of the issue, it may be an intel driver performance issue or the screen EDID that is wrongly interpreted.

**Comment by jakeday** [comment]
@thekswenson I redid some of the ipts driver and related modules for 4.14.16. Can you re-test? Please be sure to get the correct i915 firmware files in my repo now!

**Comment by fridgecow** [comment]
Seems to be working much better, using 'Google Maps' test from above.

**Comment by jakeday** [comment]
@fridgecow I still can't reproduce this oddly and the logs do not point to any issue.

**Comment by fridgecow** [comment]
Would you like me to provide a log? What would be useful?

**Comment by jakeday** [comment]
@fridgecow Can you get me the output of dmesg and the xorg log from a recent build?

**Comment by fridgecow** [comment]
Absolutely. Not sure which Xorg log is the useful one, so attached them all. Also, this problem happens on Wayland so is probably well before the X server.

[dmesg.txt](https://github.com/jakeday/linux-surface/files/1727204/dmesg.txt)
[xorglogs.tar.gz](https://github.com/jakeday/linux-surface/files/1727205/xorglogs.tar.gz)

**Comment by sebanc** [comment]
The issue seems fixed on my SP4 m3 (full resolution, no other tweaks) with the below patch applied after jakeday's 4.15 patch.
[https://gist.github.com/sebanc/6be29c1dfbba564a9a15c7b5fcbe96fc](url)

It bypasses a priority mechanism which seems not supported on Skylake guc and increases the ipts guc priority.

**Comment by jakeday** [comment]
@sebanc  Good catch! Looks like that's why it's been hit or miss as well. I'll add the changes to my kernel and we should be good.

**Comment by fridgecow** [comment]
@jakeday Can you post if/when you add it to your `.deb`s?

**Comment by jakeday** [comment]
@fridgecow Yes, absolutely!

**Comment by electrikjesus** [comment]
@sebanc 's fix also works for Surface Book & SP4 touch events on Android.

**Comment by k4ever** [comment]
How do you get the screen to auto rotate on the SP4 in Linux? Is there a script for it? Been Googling for the last 15 minutes and can only find scripts for the SP3. Using jakeday's 4.19.18 kernel in Ubuntu 18.04.

**Comment by fridgecow** [comment]
GNOME 3 has this utility built in, although it occasionally crashes for me (accelerometer stops working?)

**Comment by k4ever** [comment]
> GNOME 3 has this utility built in, although it occasionally crashes for me (accelerometer stops working?)
> […](#)
> On 29 January 2019 02:33:31 GMT, k4ever ***@***.***> wrote: How do you get the screen to auto rotate on the SP4 in Linux? Is there a script for it? Been Googling for the last 15 minutes and can only find scripts for the SP3. Using jakeday's 4.19.18 kernel in Ubuntu 18.04. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#31 (comment)](https://github.com/jakeday/linux-surface/issues/31#issuecomment-458384152)

Is there a script for other desktops or are there other desktops that support this natively? GNOME 3 is a mess. I have it installed and sure rotation works, but everything else is just plain awful! It even somehow breaks Touchegg's tweaks. I would much rather go back to Windows than use GNOME..

**Comment by fridgecow** [comment]
I believe so - when I search "KDE autorotate" a few things come up. For
lighter DEs I imagine a separate script would be necessary - but one
written for the SP3 is likely to work without much adjustment.
