### ISSUE TITLE
[Surface Book 2] slow/unreliable WiFi

### ISSUE THREAD

**Issue by nkkollaw** [jakeday/linux-surface#455]
This is the same as #324 which was closed even though the problem is still there.

I'm experiencing extremely slow and unreliable WiFi.

It goes at full speed (6MB/s) at times, but other times it won't go faster than 50KB/s.

It seems to be that the connection works normally if I use my bluetooth mouse (no idea how that's possible), and stops working a while after I stop using the mouse (maybe because the mouse goes into standby). Things don't improve if I turn bluetooth off.

It seems to be a problem with power saving, but although I have turned wifi power saving off the problem persists.

**Comment by scotty-c** [comment]
@nkkollaw I had the same issue on the 5 kernel. If you install the 4.19 it will solve your issue in the short term.

**Comment by nkkollaw** [comment]
For me, 5 completely disabled wifi, even after "waking it up" by moving a bluetooth mouse.
I reverted to 4.19 right after and on 4.19 I'm experiencing the problem described.

**Comment by nkkollaw** [comment]
Update: I have upgraded to the latest 5.x version and now it works, but still capped at 50 KB/s unless I move my mouse to "wake it up", then it goes into power saving mode again after a while.

**Comment by reganface** [comment]
I also have this issue.  I was originally on 4.19 and just recently upgraded to the 5.0.10 kernel, but the problem persists.  Connecting my phone to the surface book via bluetooth will bump up the network speeds to expected levels.  If the screen on my phone turns off from inactivity, speeds will usually drop back down again.  Waking the phone will once again boost network speeds.  For whatever reason, my bluetooth mouse does not seem to have an effect one way or the other.

**Comment by qzed** [comment]
Seems a bit like this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1505058 and https://www.spinics.net/lists/linux-wireless/msg168245.html.

Andy Shevchenko (a kernel dev) mentions that:

> The behaviour is not changed for a while.
> The workaround is to disable power management for the Wi-Fi interface and don't allow system suspend.
>
> I'm pretty sure it's a bug (or even bugs) in the firmware of Marvell products.

Can you try to disable power-saving, i.e. run `sudo iw wlp1s0 set power_save off` and see if that makes any difference (replace `wlp1s0` with your wifi interface if necessary, you can get that via `iw dev`).

**Comment by nkkollaw** [comment]
Yes, but I already have power management disabled, and it doesn't have any effect.

**Comment by qzed** [comment]
Hmm that's a bummer, I hoped that this would at least be a workaround. If it really is the firmware, we're screwed. I still want to have a look at this though when I got a bit more time.

**Comment by qzed** [comment]
So I've finally managed to test that myself. Yeah... doesn't work for me either.

**Comment by mildmenace** [comment]
SB2 user here and I notice a similar issue after installing this Kernel.

Before installing it, the wifi worked pretty well.  Sounds like I installed the wrong wifi driver.  Which driver are you using?

**Comment by mildmenace** [comment]
Is there anything further I can test to help move this issue along?

**Comment by mildmenace** [comment]
For reference, my wifi issues were solved by fixing my bluetooth.  Refer to issue #535

**Comment by nkkollaw** [comment]
Not really, it's just that moving the bluetooth mouse wakes up the wifi.

The problem persists.

**Comment by mildmenace** [comment]
You're right, I spoke too soon.
For a day, it worked completely reliably, but something change and it's back to just not working at all.

**Comment by nkkollaw** [comment]
It goes to sleep, then when you move the mouse it wakes up.

Very annoying.

**Comment by mildmenace** [comment]
My wifi doesn't work at all after a few minutes at startup, so it's worse for me.

I've resolved to literally sticking a usb wifi dongle to the back of my surface book

**Comment by nkkollaw** [comment]
Yes, but did you try connecting a bluetooth mouse and moving it? It should wake wifi up.

**Comment by mildmenace** [comment]
That does not solve my problem, unfortunately.

**Comment by nkkollaw** [comment]
Gotcha. Let's hope for a fix in the near future.

**Comment by runekaagaard** [comment]
Yes, I got it too. Weirdly enough it has been fine from the beginning. After installing some seemingly unrelated packages and bluetooth sniffing on the Surface Dial, the wifi is unusable all of the sudden. Even after complete shotdowns. Weird!

**Comment by runekaagaard** [comment]
Heh. Mr. Stoll suggested on gitter to disable bluetooth in the bios. That completely fixes the problem on my SB2.

**Comment by nkkollaw** [comment]
@runekaagaard you don't have Bluetooth, though?

**Comment by LiamMorrow** [comment]
Ah this is gold.  Disabling bluetooth in the bios fixed it entirely for me.  For ages I've just lived with using my phone as a usb tether to my wifi

**Comment by nkkollaw** [comment]
@LiamMorrow, does that mean that you can't use Bluetooth, though?

**Comment by LiamMorrow** [comment]
Yeah I don't have bluetooth now.  Definitely not ideal, but given the choices I'd prefer wifi and no bluetooth over unreliable wifi and bluetooth for my circumstance.  Very strange behaviour for sure

**Comment by slaecker** [comment]
Just wanted to add me to the list of sufferers. I can't do without Bluetooth so this issue is really annoying.

**Comment by nkkollaw** [comment]
Welcome, @slaecker!

**Comment by jaakkouu** [comment]
Yeah...
I can too notice huge difference on speed just by switching bluetooth on and off... 

Tested on Linux laptop 5.6.14-surface #1 SMP Thu May 21 11:09:43 UTC 2020 x86_64 x86_64 x86_64 GNU/

**Comment by ZiyouZhang** [comment]
Having the same issue with my SB2 here...

**Comment by LiamMorrow** [comment]
It's such a hectic behaviour. I don't even know how they could be related

**Comment by farmerbobathan** [comment]
I had this same issue, bluetooth mouse workaround and everything on my SP4 running arch linux on the newer linux-surface repo's kernel. After replacing my distro's provided `/usr/lib/firmware/mrvl` and `/usr/lib/firmware/mwlwifi` contents with the firmware from this repo, I haven't had any problems relating to wifi or bluetooth in a week of testing.
