### ISSUE TITLE
Surface Pro 4: Hibernation is broken on kernel 4.14.3 - 4.15.2

### ISSUE THREAD

**Issue by TheAlphaOne** [jakeday/linux-surface#56]
Using the most current kernel, 4.14.4 that @jakeday released, Hibernation still will not work. All steps in the guide were followed perfectly, yet using either `sudo systemctl hibernate`, pressing Suspend in the top right menu, clicking the power button and tapping Suspend, or simply shutting the type cover, all result in a full system hang and a black screen, requiring you to hold the power button for 10 seconds to force a full power down. 

Using `sudo pm-hibernate` results in hibernation, but the Surface will not power down, leaving it hanging on a black screen. When powered back on, the Surface will resume from hibernation, but WiFi is now completely missing, with NetworkManager reporting no "No WiFi capable devices found". If I restart or shutdown the Surface, the last line of text on the screen from systemd is `Reached target Shutdown` or something similar, and the Surface will freeze, requiring a hard power off.

**Comment by jameshancock144e** [comment]
Also encountering this problem, however, all my hibernate functions do hibernate but then hang at Reached Target Shutdown, no errors obvious.

**Comment by jameshancock144e** [comment]
Not to spam but also can confirm the problem is solved by downdating back to 4.14.3.

**Comment by TheAlphaOne** [comment]
@jameshancock144e Wouldn't consider it spam... Thanks for the heads-up though, will have to try it again at some point when I figure out how to compile a kernel.

**Comment by TheAlphaOne** [comment]
@jameshancock144e Not sure what Surface device you're using (Surface Pro 4 i7 256gb here), but no luck here after freshly compiling 4.14.3. Similar hibernate behavior still present with the exception being that during the shutdown process now, it simply hangs on systemd trying to end my user session, rather then the system just locking up completely. WiFi remains missing from NetworkManager after resuming from hibernation and will not come back unless I reboot/force power off.

**Comment by jakeday** [comment]
@TheAlphaOne @jameshancock144e Are you sure you aren't just getting mixed up with the changes in the files in the root folder of the repo? I've changed a couple of them recently, which may be causing issues for you.

**Comment by jameshancock144e** [comment]
I'm currently using a build of 4.14.3 from commit updating to mainline 4.14.3, but the root folder from the latest commit, mainly due to the fact I only rebuilt the kernel as an attempted fix. Between the 2, however, I also changed my swap setup so that may also have fixed it.

**Comment by jakeday** [comment]
@jameshancock144e What do you mean by changing your swap setup?

**Comment by jameshancock144e** [comment]
I setup my encrypted swap, whereas before it was just plain swap. Shouldn't have made a difference.

**Comment by TheAlphaOne** [comment]
@jakeday I'll second what @jameshancock144e is saying.. we both have the same setup apparently. Started by cloning your repo and using all the current files from git head, but I checked out 7973e098 and compiled 4.14.3 from that. Nothing else has been done other then that, awaiting any possible solution from your end...

**Comment by jameshancock144e** [comment]
I'll play around the next couple of days to see if I can find any reason why and get back on that.

**Comment by jakeday** [comment]
I know this may be obvious, but you are making sure your swap size is greater than your total amount of RAM right?

**Comment by jameshancock144e** [comment]
Yeah, 8GB RAM, 16GB Swap, wouldn't be the first time I've made dumb mistakes though. The only 2 differences I can tell are the 1 kernel version difference, and the addition of the suspend lines for devices that can make use of it, as I said before I'll play around a bit in the morning and see if I can find exactly what got it working again, it might be as simple as a config I changed somewhere along the line.

**Comment by TheAlphaOne** [comment]
@jakeday Just did some digging through the kernel log for 4.14.4 after a fresh reinstall of Ubuntu 16.04... Upon boot, I'm seeing the following:

```
Dec  9 21:42:06 surface kernel: [    0.100081] ACPI: Added _OSI(Module Device)
Dec  9 21:42:06 surface kernel: [    0.100082] ACPI: Added _OSI(Processor Device)
Dec  9 21:42:06 surface kernel: [    0.100083] ACPI: Added _OSI(3.0 _SCP Extensions)
Dec  9 21:42:06 surface kernel: [    0.100083] ACPI: Added _OSI(Processor Aggregator Device)
Dec  9 21:42:06 surface kernel: [    0.101179] ACPI Error: [_SB_.PCI0] Namespace lookup failure, AE_NOT_FOUND (20170728/dswload2-191)
Dec  9 21:42:06 surface kernel: [    0.101188] ACPI Exception: AE_NOT_FOUND, During name lookup/catalog (20170728/psobject-252)
Dec  9 21:42:06 surface kernel: [    0.101192] ACPI Error: Method parse/execution failed \_SB.PCI0.UA02, AE_NOT_FOUND (20170728/psparse-550)
Dec  9 21:42:06 surface kernel: [    0.101219] ACPI Exception: Could not find/resolve named package element: SKC1 (20170728/dspkginit-381)
Dec  9 21:42:06 surface kernel: [    0.101219] ACPI Exception: Could not find/resolve named package element: SKC2 (20170728/dspkginit-381)
```

Do you think that these ACPI errors might be the reason why hibernation is *technically* working, even though the device doesn't fully power off?

**Comment by jakeday** [comment]
@TheAlphaOne Those are not related. I'll have to put some thought into what the issue might be.

**Comment by TheAlphaOne** [comment]
Just noting something I've noticed.. the hibernate.sh script doesn't reset the WiFi at all after hibernate, and running the command `echo 1 > /sys/bus/pci/devices/0000\:02\:00.0/reset` from the script manually results in my SP4 locking up completely for around 30 seconds, then the wifi and bluetooth both become disabled completely. Trying to shutdown the SP4 results in an immediate lockup, requiring a hard power off. 

@jameshancock144e have you been experiencing anything like this with your machine?

**Comment by jakeday** [comment]
@TheAlphaOne Good catch! Taking the reset lines out results in the expected behaviors for me (although I didn't have the issue before). I'll push the change up as I don't see how doing the reset in those cases would be required anyway.

**Comment by jakeday** [comment]
@TheAlphaOne Actually, looking into this a bit and there might be a race condition in the reset process. I'm going to include a change for that in the 4.14.5 build I'm about to push. Maybe try the hibernate.sh script both with and without the reset line on the 4.14.5 build?

**Comment by TheAlphaOne** [comment]
@jakeday Alright, will do. I'll wait to see the new builds posted and I'll give them a shot.

**Comment by jakeday** [comment]
@TheAlphaOne The new builds should be up now.

**Comment by TheAlphaOne** [comment]
@jakeday Alright, some good news. WiFi does work after resuming from hibernation, but hibernation itself is still broken. My SP4 will hibernate itself when issued `sudo pm-hibernate` and `sudo systemctl hibernate`, but it still does not power off properly, it just hangs on a black screen. Using the Suspend option from the menu or pressing the power button results in a black screen and an instant system hang.

**Comment by jakeday** [comment]
@TheAlphaOne Yeah, definitely don't due suspend. Our devices do not support it and will hang. As for hibernate, can you get me a log so I can see what state acpi is putting the device in?

**Comment by thekswenson** [comment]
I'm not having problems with hibernate shutting down my SP4 on the 4.14.4 kernel.  It will reliably restore as well.

The WiFi, however, will never work after restore, even with the changes from https://github.com/jakeday/linux-surface/commit/61c6bf8a73d726cdae776f021e235d8a26d6fa04 included.

**Comment by jakeday** [comment]
@thekswenson What about 4.14.5?

**Comment by thekswenson** [comment]
I just booted up the 4.14.5 kernel and experienced the same issues as the others:
  - hibernate hangs on shutdown
  - the state will be restored
  - wifi will not work after restore and module can't be reloaded
  - machine will not longer shutdown and will give kernel null pointer errors

**Comment by TheAlphaOne** [comment]
Seconding the broken hibernation on 4.14.5... I'm unable to capture proper logs since my SP4 crashes while trying to write the log files, but I was able to capture a picture of what looks like a kernel panic(?) right before the Surface was supposed to power off. It appears the WiFi card may be one of the culprits.

On another occasion while resuming from a broken hibernation state, I briefly saw something fly across tty1 about i915 not responding, device has hung and will be reset after 15 seconds. This causes my lock screen to remain totally frozen during those 15 seconds, after which it blacks out briefly and eventually comes back up normally, but will not shutdown now without showing the error in the attached picture.

This same error appears each and every time I try to hibernate > resume > shutdown my SP4, and can be replicated over and over again.
![20171215_191257](https://user-images.githubusercontent.com/4442088/34065503-4f17bd86-e1d0-11e7-9018-1d636f73adb0.jpg)

**Comment by jrevillard** [comment]
As far as I'm concerned, Kernel 4.14.5 et Surface Book, I can hibernate and resume properly but without wifi. Here is the stack that I obtain in dmesg:

```
[  331.043068] ------------[ cut here ]------------
[  331.043093] WARNING: CPU: 1 PID: 28349 at drivers/gpu/drm/i915/i915_guc_submission.c:884 guc_init_doorbell_hw+0x172/0x1d0 [i915]
[  331.043093] Modules linked in: rfcomm input_leds xt_nat xt_tcpudp veth ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc cmac bnep btusb btrtl btbcm btintel bluetooth ecdh_generic dm_thin_pool dm_persistent_data dm_bufio dm_bio_prison libcrc32c hid_sensor_als hid_sensor_accel_3d hid_sensor_rotation hid_sensor_gyro_3d hid_sensor_trigger hid_sensor_iio_common industrialio_triggered_buffer kfifo_buf industrialio joydev hid_sensor_hub snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic mac_hid snd_soc_skl snd_soc_skl_ipc snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core snd_soc_sst_match snd_soc_core
[  331.043110]  intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm cfg80211 irqbypass intel_cstate i915 snd_hda_intel snd_hda_codec intel_rapl_perf snd_hwdep snd_hda_core snd_pcm i2c_algo_bit drm_kms_helper pcspkr snd_timer snd idma64 syscopyarea virt_dma sysfillrect soundcore sysimgblt fb_sys_fops drm ov5693(C) v4l2_common videodev media surfacepro3_button soc_button_array pinctrl_sunrisepoint video pinctrl_intel intel_lpss_acpi shpchp intel_lpss_pci tpm_crb intel_pch_thermal acpi_pad intel_lpss sch_fq_codel hid_multitouch usbhid crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 crypto_simd cryptd glue_helper nvme i2c_hid nvme_core hid autofs4 [last unloaded: mwifiex]
[  331.043130] CPU: 1 PID: 28349 Comm: kworker/u8:14 Tainted: G         C      4.14.5-surfacebook #1
[  331.043131] Hardware name: Microsoft Corporation Surface Book/Surface Book, BIOS 90.1427.768 12/19/2016
[  331.043133] Workqueue: events_unbound async_run_entry_fn
[  331.043134] task: ffff98bdcc835e00 task.stack: ffffaa2f0201c000
[  331.043150] RIP: 0010:guc_init_doorbell_hw+0x172/0x1d0 [i915]
[  331.043150] RSP: 0000:ffffaa2f0201fc78 EFLAGS: 00010286
[  331.043151] RAX: 0000000000000021 RBX: ffff98bdda9e8890 RCX: ffffffffb745f6c8
[  331.043152] RDX: 0000000000000000 RSI: 0000000000000096 RDI: 0000000000000202
[  331.043152] RBP: ffffaa2f0201fca8 R08: 0000000000000021 R09: ffffffffb792a560
[  331.043152] R10: 00000000f0000000 R11: 0000000000000021 R12: 0000000000000001
[  331.043153] R13: ffff98bddb190480 R14: ffffffffc0567888 R15: 0000000000000000
[  331.043154] FS:  0000000000000000(0000) GS:ffff98bdef480000(0000) knlGS:0000000000000000
[  331.043154] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  331.043154] CR2: 0000000000000000 CR3: 0000000246609001 CR4: 00000000003606e0
[  331.043155] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  331.043155] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  331.043156] Call Trace:
[  331.043171]  i915_guc_submission_enable+0x91/0x250 [i915]
[  331.043184]  ? gen8_guc_raise_irq+0x30/0x30 [i915]
[  331.043197]  ? gen8_guc_raise_irq+0x30/0x30 [i915]
[  331.043208]  intel_uc_init_hw+0x23b/0x340 [i915]
[  331.043221]  i915_gem_init_hw+0xf0/0x2c0 [i915]
[  331.043231]  i915_drm_resume+0x7f/0x190 [i915]
[  331.043256]  i915_pm_restore+0x1e/0x30 [i915]
[  331.043258]  pci_pm_restore+0x8e/0xd0
[  331.043260]  dpm_run_callback+0x56/0x140
[  331.043261]  ? pci_pm_suspend_noirq+0x180/0x180
[  331.043262]  device_resume+0xe1/0x1f0
[  331.043263]  async_resume+0x1d/0x50
[  331.043264]  async_run_entry_fn+0x36/0x150
[  331.043265]  process_one_work+0x1e9/0x3f0
[  331.043266]  worker_thread+0x4b/0x420
[  331.043267]  kthread+0x109/0x140
[  331.043268]  ? process_one_work+0x3f0/0x3f0
[  331.043269]  ? kthread_create_on_node+0x70/0x70
[  331.043271]  ret_from_fork+0x25/0x30
[  331.043272] Code: 41 83 c4 01 41 81 fc 00 01 00 00 74 2d 44 89 e6 48 89 df e8 61 f9 ff ff 84 c0 75 e4 4c 89 f6 48 c7 c7 ef 65 55 c0 e8 5f a5 03 f6 <0f> ff 41 83 c4 01 41 81 fc 00 01 00 00 75 d3 48 83 c4 08 44 89 
[  331.043286] ---[ end trace b01750eb627fd5fd ]---
```

Best,
Jerome

**Comment by jakeday** [comment]
@jrevillard Which version of the hibernate.sh script are you using? The one with the reset lines or the one without?

**Comment by jrevillard** [comment]
I tried both, currently I use the one without the reset and the stack comes from this version.

**Comment by jakeday** [comment]
@TheAlphaOne Can you please try the latest 4.14.8 build?

**Comment by jrevillard** [comment]
@jakeday I just tested and it works for me on my surfacebook !! Thanks!

**Comment by TheAlphaOne** [comment]
@jakeday Just did a full reinstall of Ubuntu 16.04 on my SP4, running your latest build, the same behavior is still present. No changes whatsoever. The SP4 will not go into hibernation and power off correctly, and WiFi does not function at all upon resume. Below is a crash log I managed to capture from dmesg upon resume.

[mwifiex_pcie.txt](https://github.com/jakeday/linux-surface/files/1587949/mwifiex_pcie.txt)

**Comment by eskinderg** [comment]
@jakeday any instructions on how to try out the new builds, I tried git pull from my /root directory and repeated all the steps. I don't know if that's the right way of doing it.

**Comment by jrevillard** [comment]
@jakeday , it works most of the time but some time, I still have th issue with this Kernel error:

```
[51616.675712] ------------[ cut here ]------------
[51616.675737] WARNING: CPU: 2 PID: 3729 at drivers/gpu/drm/i915/intel_drv.h:1767 intel_uncore_forcewake_get+0xa1/0xb0 [i915]
[51616.675737] Modules linked in: intel_ipts mei_me mei uhid algif_hash algif_skcipher af_alg hid_generic hidp rfcomm xt_nat xt_tcpudp veth ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc ax88179_178a usbnet mii cmac uas usb_storage dm_thin_pool dm_persistent_data dm_bufio dm_bio_prison libcrc32c bnep btusb btrtl btbcm btintel bluetooth ecdh_generic input_leds usbhid snd_hda_codec_hdmi snd_hda_codec_realtek joydev snd_hda_codec_generic hid_multitouch hid_sensor_accel_3d hid_sensor_gyro_3d hid_sensor_rotation hid_sensor_als hid_sensor_trigger hid_sensor_iio_common industrialio_triggered_buffer kfifo_buf
[51616.675759]  industrialio hid_sensor_hub i915 cfg80211 mac_hid snd_soc_skl snd_soc_skl_ipc snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core snd_soc_sst_match snd_soc_core intel_rapl x86_pkg_temp_thermal intel_powerclamp i2c_algo_bit coretemp drm_kms_helper kvm_intel kvm syscopyarea snd_hda_intel sysfillrect snd_hda_codec sysimgblt irqbypass fb_sys_fops intel_cstate drm snd_hwdep snd_hda_core intel_rapl_perf snd_pcm snd_timer pcspkr snd ov5693(C) soundcore idma64 v4l2_common virt_dma videodev shpchp intel_pch_thermal intel_lpss_pci media soc_button_array surfacepro3_button pinctrl_sunrisepoint pinctrl_intel intel_lpss_acpi video acpi_pad intel_lpss tpm_crb sch_fq_codel crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 crypto_simd cryptd glue_helper nvme nvme_core i2c_hid hid
[51616.675784]  autofs4 [last unloaded: mwifiex]
[51616.675786] CPU: 2 PID: 3729 Comm: ipts_event_thre Tainted: G        WC      4.14.8-surfacebook #1
[51616.675786] Hardware name: Microsoft Corporation Surface Book/Surface Book, BIOS 90.1427.768 12/19/2016
[51616.675787] task: ffff8d1f51d61780 task.stack: ffffbadc82d1c000
[51616.675804] RIP: 0010:intel_uncore_forcewake_get+0xa1/0xb0 [i915]
[51616.675804] RSP: 0018:ffffbadc82d1fb80 EFLAGS: 00010282
[51616.675805] RAX: 000000000000002a RBX: ffff8d1f98a68000 RCX: ffffffff9a65f6c8
[51616.675806] RDX: 0000000000000000 RSI: 0000000000000096 RDI: 0000000000000247
[51616.675806] RBP: ffffbadc82d1fba0 R08: 000000000000002a R09: 0000000000001254
[51616.675807] R10: ffffbadc82d1fcd0 R11: 000000000000002a R12: 0000000000000002
[51616.675807] R13: 0000000000000000 R14: ffffbadc82d1fc08 R15: ffff8d1f98a68890
[51616.675808] FS:  0000000000000000(0000) GS:ffff8d1faf500000(0000) knlGS:0000000000000000
[51616.675809] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[51616.675809] CR2: 00007fd24511e1d0 CR3: 00000002cb809003 CR4: 00000000003606e0
[51616.675810] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[51616.675811] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[51616.675811] Call Trace:
[51616.675827]  intel_guc_send_mmio+0x59/0x160 [i915]
[51616.675840]  ? i915_mutex_lock_interruptible+0x42/0x140 [i915]
[51616.675854]  i915_guc_ipts_reacquire_doorbell+0x49/0x80 [i915]
[51616.675869]  intel_ipts_reacquire_db.isra.7+0x25/0x50 [i915]
[51616.675883]  intel_ipts_get_wq_info+0x7d/0xc0 [i915]
[51616.675885]  ipts_open_gpu+0x8c/0xb0 [intel_ipts]
[51616.675886]  ? notify_gfx_status+0x30/0x30 [intel_ipts]
[51616.675887]  ? ipts_set_output_buffer+0x30/0x30 [intel_ipts]
[51616.675900]  ? intel_ipts_map_buffer+0x2f0/0x2f0 [i915]
[51616.675913]  ? intel_ipts_disconnect+0x70/0x70 [i915]
[51616.675925]  ? reacquire_db_work_func+0xb0/0xb0 [i915]
[51616.675926]  ipts_init_kernels+0x2f/0xf0 [intel_ipts]
[51616.675927]  ? ipts_init_kernels+0x2f/0xf0 [intel_ipts]
[51616.675928]  ipts_allocate_raw_data_resource+0x12/0x20 [intel_ipts]
[51616.675930]  ipts_handle_resp+0x3f2/0x5b0 [intel_ipts]
[51616.675934]  ? mei_io_cb_free+0x4c/0x50 [mei]
[51616.675936]  ? kfree+0x14a/0x160
[51616.675936]  ? kfree+0x14a/0x160
[51616.675939]  ? mei_io_cb_free+0x4c/0x50 [mei]
[51616.675941]  ? __mei_cl_recv+0x66/0x1f0 [mei]
[51616.675943]  ? wait_woken+0x80/0x80
[51616.675944]  ipts_mei_cl_event_thread+0x52/0xb0 [intel_ipts]
[51616.675946]  kthread+0x109/0x140
[51616.675947]  ? init_work_func+0x30/0x30 [intel_ipts]
[51616.675948]  ? kthread_create_on_node+0x70/0x70
[51616.675950]  ? do_syscall_64+0x61/0x120
[51616.675951]  ? SyS_exit_group+0x14/0x20
[51616.675953]  ret_from_fork+0x25/0x30
[51616.675953] Code: 05 a7 bc 0e 00 01 e8 a0 5f e4 d8 0f ff eb a4 80 3d 96 bc 0e 00 00 75 a5 48 c7 c7 28 f5 95 c0 c6 05 86 bc 0e 00 01 e8 80 5f e4 d8 <0f> ff eb 8e 90 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 
[51616.675971] ---[ end trace cdb72f550cfab28d ]---
```

Best,
Jerome

**Comment by jrevillard** [comment]
@jakeday I confirm that your fix works only for the first hibernation for me. If you try to hibernate a second time, I have the kernel panic.
Should you re-open this issue or should I open a new one ?

Best.

**Comment by TheAlphaOne** [comment]
@jrevillard This should've never been closed in the first place. I'm hoping @jakeday sees this and reopens it. Someone jumped the gun by closing it before the problem was fixed. 😒

**Comment by jakeday** [comment]
@TheAlphaOne I apologize, I saw the comment saying the last push fixed it and assumed we were good. Re-opened it.

**Comment by dpedu** [comment]
Throwing in another data point - on my Surface Book 2 13" with a fresh ubuntu 17.04 install, hibernation works perfectly with the `4.14.8-surface-jakeday` kernel, though I need to call it manually via `sudo systemctl hibernate`. A second hibernation seems OK too.

What doesn't work is auto-hibernation. This is Gnome specific, but as described [here](http://ubuntuhandbook.org/index.php/2016/05/ubuntu-16-04-shutdown-hibernate-your-laptop-lid-closed/), I made hibernate the default handler for various actions (such as lid close and power button press) but hibernation does not occur when performing any of these actions.

**Comment by TheAlphaOne** [comment]
@jakeday Here's a log I was finally able to capture as the SP4 goes into, and comes out of hibernation. Looks to be an issue with the i915 driver maybe?

[hibernate_crash.txt](https://github.com/jakeday/linux-surface/files/1596366/hibernate_crash.txt)

**Comment by oleid** [comment]
@dpedu : I call "systemctl hibernate" manually, too. But re-waking, wifi is gone. Even for the first time. I get a similar log than @TheAlphaOne on my SP4 on Ubuntu 17.10.

**Comment by notdisliked** [comment]
I'm currently having problems with hibernate on 17.10.1 on the most recent kernel.  Downloading 17.04 to try out too, and will try out some of the specific kernel versions listed in this thread.  For me, mapping suspend to hibernate seems to be working, but when I suspend (hibernate) the screen turns off, then back on a few seconds later.  The same happens with `sudo systemctl hibernate`.  When the screen comes back on wifi, touchscreen, pen support, and most things enabled with the kernel don't work.

**Comment by jakeday** [comment]
I can no longer reproduce this on my newer setup with my latest kernels. Can you guys please re-test with 4.14.14?

**Comment by TheAlphaOne** [comment]
@jakeday After installing the newest 4.14.14 builds from your Google Drive, similar issues are still happening on my SP4. Good news though, WiFi does not crash now after resuming from hibernation, although getting into hibernation is still only somewhat working. Firing off a `sudo systemctl hibernate` does indeed hibernate the system, but the touch cover keys remain lit when pressed, indicating that it is not fully powering off as it should. It seems there is something still acting up with the internal graphics upon resume as well, causing the stack in the attached dmesg log.

Attached, I will leave a full dmesg, lshw, and lspci log for you to look through if you need more information on my particular setup for any reason.

[dmesg.txt](https://github.com/jakeday/linux-surface/files/1649307/dmesg.txt)
[lshw.txt](https://github.com/jakeday/linux-surface/files/1649308/lshw.txt)
[lspci.txt](https://github.com/jakeday/linux-surface/files/1649309/lspci.txt)

**Comment by jrevillard** [comment]
Same problem than for @TheAlphaOne now. Wifi working properly but hibernation is not always working.

I don't know if it could help but I see this quite often into the logs

```
janv. 21 18:23:18 ordiwork kernel: ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: touch enabled 4
janv. 21 18:23:18 ordiwork kernel: [drm] Reducing the compressed framebuffer size. This may lead to less power savings than a non-reduced-size. Try to increase stolen memory size if available in BIOS.
```

The first message about ipts mei.. is red by the way... is it an error ?

Best,
Jerome

**Comment by jakeday** [comment]
Can you give this a shot on 4.14.16? I'm no longer able to reproduce.

**Comment by jakeday** [comment]
Also, if you have tlp installed please try without it as well. I've seen it cause some hiccups with hibernate.

**Comment by TheAlphaOne** [comment]
@jakeday Still no dice... tlp is not installed. dmesg logs attached. I will make an attempt at filming or capturing a picture of the screen as it goes into and comes out of hibernation, there are other errors present that I cannot capture due to the screen clearing itself.


[dmesg.txt](https://github.com/jakeday/linux-surface/files/1691136/dmesg.txt)

**Comment by TheAlphaOne** [comment]
https://youtu.be/LmR0ZACHHmA
https://youtu.be/7xhgbgCOjYY

@jakeday Got a little bit of footage.. it's a little blurry, phone doesn't like focusing on the screen. 

You can see how it goes into and comes out of Hibernation with the errors.

**Comment by xaviervilla** [comment]
I'm not sure how hibernation in Ubuntu is handled, so I'm not sure if mine is working properly.. Hibernate appears to work fine, but it turns my surfacebook all the way off, and when I boot again and go through grub, my windows are still open. However, in Windows 10 It keeps the Surfacebook turned on when you open the lid, and it just picks back up where you left off. Why is that hibernation for Windows 10 different than with Ubuntu? is this because my hibernation isn't working properly? I'd like to add that wifi and everything still works after multiple hibernation cycles. I'm just unsure if powering 100% off is normal.

**Comment by TheAlphaOne** [comment]
@xaviervilla Can we get a few more details on your setup, like what kind of Surface product you're using, what Ubuntu revision, etc?

Also, if your Surface is actually hibernating in Windows 10, it should not be turning back on by simply opening the lid, I think you're confusing that with Connected Standby/Sleep mode. If you were fully hibernating the system, it'd be the same as powering off the device fully, and having to press the power button to turn it back on.

**Comment by TheAlphaOne** [comment]
@jakeday Noticing something strange happening here now.

-`sudo systemctl hibernate` results in hibernation that properly saves the user state but doesn't power down the SP4. It resumes from hibernation with WiFi intact, but still results in the crashes like I posted above.
-`sudo pm-hibernate` results in proper hibernation that actually powers down the SP4, but on resume, the console is spammed with errors about the GPU hanging, and any subsequent attempts to power down the system normally with a `sudo poweroff` or trying to put it into hibernation result in full system lockup. WiFi does not work at all on resume either...

Here's a new dmesg log after running the `pm-hibernate` command: [dmesg.txt](https://github.com/jakeday/linux-surface/files/1692413/dmesg.txt)

**Comment by xaviervilla** [comment]
Yes, I'm on the i5 6300U - 8GB Surface Book (no GPU/performance base). Running Ubuntu 16.04.3 (Fresh install yesterday and followed the readme step by step with no problems). I went with the pre-built kernel and header that you had up (I was unsure which version I needed so chose the highest number - 4.15.0) Yesterday Everything was working beautifully, and it seems hibernation is working as expected with wifi never having issues as some users above reported. Today, however, I noticed the touch screen isn't working anymore, I'm going to try rebooting and see if that helps.

**Comment by xaviervilla** [comment]
Reboting fixed the touch screen btw.

**Comment by TheAlphaOne** [comment]
@jakeday You're gonna get real sick of this particular issue soon, I can see it coming. 🤣 

Tried hibernation (systemctl hibernate/pm-hibernate) both on 4.14.18 and the newest 4.15.2, both result in the same issues and same errors (as far as I can tell) as previously mentioned in https://github.com/jakeday/linux-surface/issues/56#issuecomment-362877002 

Attached is a new dmesg log if you need it. 

[dmesg.txt](https://github.com/jakeday/linux-surface/files/1708836/dmesg.txt)

**Comment by jrevillard** [comment]
A quick update for 4.14.18. Wifi does not work after resume:

févr. 13 08:54:45 ordiwork kernel: ------------[ cut here ]------------
févr. 13 08:54:45 ordiwork kernel: WARNING: CPU: 1 PID: 9119 at drivers/gpu/drm/i915/i915_guc_submission.c:884 guc_init_doorbell_hw+0x179/0x1d0 [i915]
févr. 13 08:54:45 ordiwork kernel: Modules linked in: ppp_deflate bsd_comp ppp_async nls_iso8859_1 btrfs xor zstd_decompress zstd_compress xxhash raid6_pq ntfs msdos jfs xfs ax88179_178a usbnet mii hid_generic hidp rfcomm xt_nat xt_tcpudp veth ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc input_leds usbhid cmac dm_thin_pool dm_persistent_data dm_bufio dm_bio_prison libcrc32c bnep btusb btrtl btbcm btintel bluetooth ecdh_generic snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic uas joydev usb_storage hid_multitouch intel_ipts hid_sensor_gyro_3d hid_sensor_accel_3d hid_sensor_rotation hid_sensor_als hid_sensor_trigger
févr. 13 08:54:45 ordiwork kernel:  hid_sensor_iio_common industrialio_triggered_buffer kfifo_buf industrialio hid_sensor_hub i915 snd_soc_skl mac_hid snd_soc_skl_ipc mwifiex_pcie snd_soc_sst_ipc mwifiex snd_soc_sst_dsp snd_hda_ext_core snd_soc_sst_match cfg80211 snd_soc_core intel_rapl x86_pkg_temp_thermal i2c_algo_bit intel_powerclamp drm_kms_helper coretemp syscopyarea kvm_intel sysfillrect sysimgblt snd_hda_intel kvm snd_hda_codec fb_sys_fops drm irqbypass snd_hwdep intel_cstate snd_hda_core intel_rapl_perf snd_pcm snd_timer pcspkr snd idma64 soundcore ov5693(C) mei_me virt_dma v4l2_common intel_pch_thermal mei videodev shpchp intel_lpss_pci media intel_lpss acpi_pad pinctrl_sunrisepoint soc_button_array surfacepro3_button video tpm_crb pinctrl_intel sch_fq_codel vboxpci(OE) vboxnetadp(OE) vboxnetflt(OE) vboxdrv(OE)
févr. 13 08:54:45 ordiwork kernel:  crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 crypto_simd cryptd glue_helper nvme i2c_hid nvme_core hid
févr. 13 08:54:45 ordiwork kernel: CPU: 1 PID: 9119 Comm: kworker/u8:11 Tainted: G     U   C OE   4.14.18-surface-surfacebook #1
févr. 13 08:54:45 ordiwork kernel: Hardware name: Microsoft Corporation Surface Book/Surface Book, BIOS 91.1926.768 12/06/2017
févr. 13 08:54:45 ordiwork kernel: Workqueue: events_unbound async_run_entry_fn
févr. 13 08:54:45 ordiwork kernel: task: ffff8cf70ca49780 task.stack: ffff9dde82390000
févr. 13 08:54:45 ordiwork kernel: RIP: 0010:guc_init_doorbell_hw+0x179/0x1d0 [i915]
févr. 13 08:54:45 ordiwork kernel: RSP: 0000:ffff9dde82393d00 EFLAGS: 00010286
févr. 13 08:54:45 ordiwork kernel: RAX: 0000000000000021 RBX: 0000000000000001 RCX: ffffffffa9861648
févr. 13 08:54:45 ordiwork kernel: RDX: 0000000000000000 RSI: 0000000000000082 RDI: 0000000000000202
févr. 13 08:54:45 ordiwork kernel: RBP: ffff8cf718698890 R08: 0000000000000021 R09: 0000000000000021
févr. 13 08:54:45 ordiwork kernel: R10: 00000000f0000000 R11: 0000000000000733 R12: ffff8cf70c4e0180
févr. 13 08:54:45 ordiwork kernel: R13: ffffffffc0969858 R14: 0000000000000000 R15: 0000000000000100
févr. 13 08:54:45 ordiwork kernel: FS:  0000000000000000(0000) GS:ffff8cf72f480000(0000) knlGS:0000000000000000
févr. 13 08:54:45 ordiwork kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
févr. 13 08:54:45 ordiwork kernel: CR2: 0000000000000000 CR3: 0000000379c0a001 CR4: 00000000003606e0
févr. 13 08:54:45 ordiwork kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
févr. 13 08:54:45 ordiwork kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
févr. 13 08:54:45 ordiwork kernel: Call Trace:
févr. 13 08:54:45 ordiwork kernel:  ? gen8_guc_raise_irq+0x30/0x30 [i915]
févr. 13 08:54:45 ordiwork kernel:  i915_guc_submission_enable+0x89/0x230 [i915]
févr. 13 08:54:45 ordiwork kernel:  ? gen8_guc_raise_irq+0x30/0x30 [i915]
févr. 13 08:54:45 ordiwork kernel:  intel_uc_init_hw+0x22d/0x330 [i915]
févr. 13 08:54:45 ordiwork kernel:  i915_gem_init_hw+0xdb/0x290 [i915]
févr. 13 08:54:45 ordiwork kernel:  ? pci_pm_suspend_noirq+0x170/0x170
févr. 13 08:54:45 ordiwork kernel:  i915_drm_resume+0x7a/0x190 [i915]
févr. 13 08:54:45 ordiwork kernel:  dpm_run_callback+0x4d/0x140
févr. 13 08:54:45 ordiwork kernel:  device_resume+0xd3/0x1f0
févr. 13 08:54:45 ordiwork kernel:  async_resume+0x19/0x40
févr. 13 08:54:45 ordiwork kernel:  async_run_entry_fn+0x31/0x140
févr. 13 08:54:45 ordiwork kernel:  process_one_work+0x1e0/0x3d0
févr. 13 08:54:45 ordiwork kernel:  worker_thread+0x4a/0x410
févr. 13 08:54:45 ordiwork kernel:  kthread+0xfc/0x130
févr. 13 08:54:45 ordiwork kernel:  ? process_one_work+0x3d0/0x3d0
févr. 13 08:54:45 ordiwork kernel:  ? kthread_create_on_node+0x70/0x70
févr. 13 08:54:45 ordiwork kernel:  ret_from_fork+0x35/0x40
févr. 13 08:54:45 ordiwork kernel: Code: 0d eb 47 83 c3 01 81 fb 00 01 00 00 74 2a 89 de 48 89 ef e8 7a f9 ff ff 84 c0 75 e7 4c 89 ee 48 c7 c7 cf 85 95 c0 e8 c2 f8 e2 e7 <0f> ff 83 c3 01 81 fb 00 01 00 00 75 d6 48 83 c4 08 44 89 f0 5b 
févr. 13 08:54:45 ordiwork kernel: ---[ end trace 25ecdaa3fd7599c4 ]---


After, I have regularly this messages in the logs:

févr. 13 08:57:30 ordiwork kernel: INFO: task kworker/0:1:9117 blocked for more than 120 seconds.
févr. 13 08:57:30 ordiwork kernel:       Tainted: G     U  WC OE   4.14.18-surface-surfacebook #1
févr. 13 08:57:30 ordiwork kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
févr. 13 08:57:30 ordiwork kernel: kworker/0:1     D    0  9117      2 0x80000000
févr. 13 08:57:30 ordiwork kernel: Workqueue: events mwifiex_pcie_work [mwifiex_pcie]
févr. 13 08:57:30 ordiwork kernel: Call Trace:
févr. 13 08:57:30 ordiwork kernel:  ? __schedule+0x3c8/0x850
févr. 13 08:57:30 ordiwork kernel:  ? __clear_rsb+0x25/0x3d
févr. 13 08:57:30 ordiwork kernel:  ? __clear_rsb+0x15/0x3d
févr. 13 08:57:30 ordiwork kernel:  ? work_busy+0xa0/0xa0
févr. 13 08:57:30 ordiwork kernel:  schedule+0x32/0x80
févr. 13 08:57:30 ordiwork kernel:  schedule_timeout+0x1d5/0x370
févr. 13 08:57:30 ordiwork kernel:  ? __switch_to+0xa8/0x450
févr. 13 08:57:30 ordiwork kernel:  ? __clear_rsb+0x15/0x3d
févr. 13 08:57:30 ordiwork kernel:  ? __clear_rsb+0x15/0x3d
févr. 13 08:57:30 ordiwork kernel:  ? work_busy+0xa0/0xa0
févr. 13 08:57:30 ordiwork kernel:  ? wait_for_completion+0xb9/0x140
févr. 13 08:57:30 ordiwork kernel:  wait_for_completion+0xb9/0x140
févr. 13 08:57:30 ordiwork kernel:  ? wake_up_q+0x70/0x70
févr. 13 08:57:30 ordiwork kernel:  flush_work+0x11b/0x1d0
févr. 13 08:57:30 ordiwork kernel:  ? worker_detach_from_pool+0xa0/0xa0
févr. 13 08:57:30 ordiwork kernel:  __cancel_work_timer+0x10f/0x190
févr. 13 08:57:30 ordiwork kernel:  ? wait_for_completion+0xc4/0x140
févr. 13 08:57:30 ordiwork kernel:  ? wake_up_q+0x70/0x70
févr. 13 08:57:30 ordiwork kernel:  mwifiex_cleanup_pcie+0x29/0xce [mwifiex_pcie]
févr. 13 08:57:30 ordiwork kernel:  mwifiex_free_adapter+0x23/0xf0 [mwifiex]
févr. 13 08:57:30 ordiwork kernel:  _mwifiex_fw_dpc+0x180/0x4c0 [mwifiex]
févr. 13 08:57:30 ordiwork kernel:  ? request_firmware+0x3b/0x50
févr. 13 08:57:30 ordiwork kernel:  ? mwifiex_init_hw_fw+0x71/0xf0 [mwifiex]
févr. 13 08:57:30 ordiwork kernel:  mwifiex_reinit_sw+0x162/0x2d0 [mwifiex]
févr. 13 08:57:30 ordiwork kernel:  mwifiex_pcie_reset_done+0x4c/0xb0 [mwifiex_pcie]
févr. 13 08:57:30 ordiwork kernel:  pci_try_reset_function+0x5f/0x70
févr. 13 08:57:30 ordiwork kernel:  mwifiex_pcie_work+0x58/0x3f0 [mwifiex_pcie]
févr. 13 08:57:30 ordiwork kernel:  ? __clear_rsb+0x15/0x3d
févr. 13 08:57:30 ordiwork kernel:  process_one_work+0x1e0/0x3d0
févr. 13 08:57:30 ordiwork kernel:  worker_thread+0x4a/0x410
févr. 13 08:57:30 ordiwork kernel:  kthread+0xfc/0x130
févr. 13 08:57:30 ordiwork kernel:  ? process_one_work+0x3d0/0x3d0
févr. 13 08:57:30 ordiwork kernel:  ? kthread_create_on_node+0x70/0x70
févr. 13 08:57:30 ordiwork kernel:  ? SyS_exit_group+0x10/0x10
févr. 13 08:57:30 ordiwork kernel:  ret_from_fork+0x35/0x40


Best,
Jerome

**Comment by junghyuneun** [comment]
For anyone having problem with touchscreen, check if the module "i2c_hid" is up after waking up / reattach, etc by doing "lsmod | grep i2c_hid". If it is not up, try doing "modprobe -a i2c_hid" and see if touchscreen works.

**Comment by jrevillard** [comment]
@jakeday Do you still have problems to reproduce ? I'm still able to wake up but I have no more Wifi/Bluetooth (see my segfault). I'm using 4.15.4 now. Do you need specific information to be able to fix it (if possible ;-) )

Best,
Jerome

**Comment by Zyfarok** [comment]
Just wondering if my #119 pull request could possibly be related

**Comment by jakeday** [comment]
This has been fixed in 4.15.15.

**Comment by battaglia01** [comment]
FWIW I still have this problem on SP4 running Neon and using the 4.16.0 kernel, which I compiled myself. I used the patches in the 4.16 directory (which seemed to patch correctly). Were the 4.16 patches in the repo updated with this fix?

**Comment by TheAlphaOne** [comment]
Hate to reawaken this old issue, but hibernation seems to not be working on 4.18.11... Recently did a fresh install of Ubuntu 18.04 on my SP4. Same issues as my first post.

**Comment by xgenvn** [comment]
Hi, I'm on the Surface Pro 4, Ubuntu 18.04.1, latest kernel:
```
4.18.20-surface-linux-surface
```
It seems I have same problem that the Hibernation is actually shutting down and I can not recover from last state.
Touchscreen sometimes drops, wifi also drops once/twice.
I setup the swap space for 4GB. The installation is on the same drive with Windows.
Is there any solution I can try to get the hibernation/suspend working?

Thanks.

**Comment by oleid** [comment]
> Hi, I'm on the Surface Pro 4, Ubuntu 18.04.1, latest kernel:
> 4.18.20-surface-linux-surface
> [...]
> Is there any solution I can try to get the hibernation/suspend working?

How do you hibernate? I'm asking, since it works fine here for on my SP4 on debian testing.
Does `systemctl hibernate` work for you?

**Comment by xgenvn** [comment]
> > Hi, I'm on the Surface Pro 4, Ubuntu 18.04.1, latest kernel:
> > 4.18.20-surface-linux-surface
> > [...]
> > Is there any solution I can try to get the hibernation/suspend working?
> 
> How do you hibernate? I'm asking, since it works fine here for on my SP4 on debian testing.
> Does `systemctl hibernate` work for you?

Hi, I have just tested it but unfortunately the system could not recover from last state.

I take a look on `dmesg` and see this, not sure if it's related to my issue:
```
[   14.810850] systemd-journald[294]: File /var/log/journal/8373473aa28b4a11aadacfc60cb2d1c8/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
```

**Comment by oleid** [comment]
Does hibernate work four you using a recent mainline kernel? I.e. https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.13/

**Comment by xgenvn** [comment]
@oleid I install `ukuu` then update to latest mainline kernel, which is: `4.20.0-042000-generic`. 
After enabling swap in grub entry (like I did before), I can restore the state. Bluetooth and Wifi are both working fine.
