### ISSUE TITLE
Surface Pro 3: WiFi Stability Issues

### ISSUE THREAD

**Issue by Gunkkk** [jakeday/linux-surface#74]
The wifi will just go wrong after my pro3 turned on for serval seconds 
You can imagine that how serious it is.What should i do to solve the problem please

Also when i touch the power button ,the screen couldnt be back ,is that normal?

**Comment by Gunkkk** [comment]
Linux version 4.13.0-26-generic

**Comment by jakeday** [comment]
@Gunkkk Neither of those sound normal. Can you get me some logs?

**Comment by Gunkkk** [comment]
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9206] manager: sleep requested (sleeping: no  enabled: yes)
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9206] manager: sleeping...
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9207] device (8C:0D:76:E8:64:83): state change: disconnected -> unmanaged (reason 'sleeping') [30 10 37]
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9209] manager: NetworkManager state is now ASLEEP
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9213] device (wlp1s0): state change: activated -> deactivating (reason 'sleeping') [100 110 37]
Jan 19 10:52:39 Gunkkk whoopsie[912]: [10:52:39] offline
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9371] device (wlp1s0): state change: deactivating -> disconnected (reason 'sleeping') [110 30 37]
Jan 19 10:52:39 Gunkkk avahi-daemon[804]: Withdrawing address record for fe80::f11d:d28a:75eb:253a on wlp1s0.
Jan 19 10:52:39 Gunkkk avahi-daemon[804]: Leaving mDNS multicast group on interface wlp1s0.IPv6 with address fe80::f11d:d28a:75eb:253a.
Jan 19 10:52:39 Gunkkk avahi-daemon[804]: Interface wlp1s0.IPv6 no longer relevant for mDNS.
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9705] dhcp4 (wlp1s0): canceled DHCP transaction, DHCP client pid 1146
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9705] dhcp4 (wlp1s0): state changed bound -> done
Jan 19 10:52:39 Gunkkk wpa_supplicant[1087]: wlp1s0: CTRL-EVENT-DISCONNECTED bssid=f4:83:cd:f9:3e:42 reason=3 locally_generated=1
Jan 19 10:52:39 Gunkkk kernel: [ 1365.078746] mwifiex_pcie 0000:01:00.0: info: successfully disconnected from f4:83:cd:f9:3e:42: reason code 3
Jan 19 10:52:39 Gunkkk NetworkManager[812]: <info>  [1516330359.9783] dns-mgr: Removing DNS information from /sbin/resolvconf
Jan 19 10:52:39 Gunkkk avahi-daemon[804]: Withdrawing address record for 192.168.1.118 on wlp1s0.
Jan 19 10:52:39 Gunkkk avahi-daemon[804]: Leaving mDNS multicast group on interface wlp1s0.IPv4 with address 192.168.1.118.
Jan 19 10:52:39 Gunkkk whoopsie[912]: [10:52:39] Cannot reach: https://daisy.ubuntu.com


Jan 19 10:52:45 Gunkkk systemd[1]: Reached target Sleep.
Jan 19 10:52:45 Gunkkk systemd[1]: Starting Suspend...
Jan 19 10:52:45 Gunkkk systemd-sleep[3630]: Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory
Jan 19 10:52:45 Gunkkk systemd-sleep[3631]: /lib/systemd/system-sleep/wpasupplicant failed with error code 255.
Jan 19 10:52:45 Gunkkk systemd[1]: Stopped Network Manager Wait Online.
Jan 19 10:52:45 Gunkkk systemd[1]: Stopping Network Manager...
Jan 19 10:52:45 Gunkkk NetworkManager[812]: <info>  [1516330365.1857] caught SIGTERM, shutting down normally.
Jan 19 10:52:45 Gunkkk NetworkManager[812]: <info>  [1516330365.1872] exiting (success)
Jan 19 10:52:45 Gunkkk systemd[1]: Stopped Network Manager.
Jan 19 10:52:45 Gunkkk systemd-sleep[3630]: rmmod: ERROR: Module intel_ipts is not currently loaded
Jan 19 10:52:45 Gunkkk gnome-session[963]: Gjs-Message: JS LOG: Removing a network device that was not added
Jan 19 10:52:45 Gunkkk gnome-session[1302]: Gjs-Message: JS LOG: Removing a network device that was not added
Jan 19 10:52:45 Gunkkk kernel: [ 1370.412939] mwifiex_pcie 0000:01:00.0: info: shutdown mwifiex...
Jan 19 10:52:45 Gunkkk kernel: [ 1370.413420] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 19 10:52:45 Gunkkk systemd[1]: Starting Load/Save RF Kill Switch Status...
Jan 19 10:52:45 Gunkkk systemd[1]: Started Load/Save RF Kill Switch Status.
Jan 19 10:52:45 Gunkkk systemd-sleep[3630]: Suspending system...

## The log above may be the msg of suspend problem .But  I'm  a fresh man and  not sure about that.

## The following msg may be  the wifi problem And the problem has been solved after updating my system.

Jan 19 00:14:40 Gunkkk NetworkManager[796]: <warn>  [1516292080.4594] device (wlp1s0): Activation: (wifi) association took too long, failing activation
Jan 19 00:14:40 Gunkkk NetworkManager[796]: <info>  [1516292080.4594] device (wlp1s0): state change: config -> failed (reason 'ssid-not-found') [50 120 53]
Jan 19 00:14:40 Gunkkk NetworkManager[796]: <info>  [1516292080.4597] manager: NetworkManager state is now DISCONNECTED
Jan 19 00:14:40 Gunkkk NetworkManager[796]: <warn>  [1516292080.4603] device (wlp1s0): Activation: failed for connection 'TP-LINK_FDD2'
Jan 19 00:14:40 Gunkkk NetworkManager[796]: <info>  [1516292080.4610] device (wlp1s0): state change: failed -> disconnected (reason 'none') [120 30 0]
Jan 19 00:14:40 Gunkkk kernel: [  309.003034] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
Jan 19 00:14:42 Gunkkk anacron[725]: Job `cron.daily' terminated
Jan 19 00:14:42 Gunkkk anacron[725]: Normal exit (1 job run)
Jan 19 00:14:52 Gunkkk wpa_supplicant[1051]: wlp1s0: Failed to initiate sched scan
Jan 19 00:14:52 Gunkkk wpa_supplicant[1051]: wlp1s0: Failed to initiate sched scan
Jan 19 00:14:52 Gunkkk NetworkManager[796]: <info>  [1516292092.7041] device (wlp1s0): supplicant interface state: inactive -> disconnected
Jan 19 00:14:52 Gunkkk kernel: [  321.244101] mwifiex_pcie 0000:01:00.0: cmd_wait_q terminated: -110
Jan 19 00:14:52 Gunkkk kernel: [  321.244502] ieee80211 phy0: mwifiex_cfg80211_sched_scan_start : Invalid Sched_scan parameters
Jan 19 00:14:52 Gunkkk kernel: [  321.245017] ieee80211 phy0: mwifiex_cfg80211_sched_scan_start : Invalid Sched_scan parameters
Jan 19 00:14:52 Gunkkk NetworkManager[796]: <info>  [1516292092.7244] device (wlp1s0): supplicant interface state: disconnected -> inactive
Jan 19 00:14:55 Gunkkk wpa_supplicant[1051]: wlp1s0: Reject scan trigger since one is already pending
Jan 19 00:14:56 Gunkkk gnome-session[1266]: (gnome-control-center:2685): Clutter-WARNING **: Whoever translated default:LTR did so wrongly.
Jan 19 00:14:56 Gunkkk gnome-session[1266]: ** (gnome-control-center:2685): WARNING **: Ignoring launcher gufw (missing desktop file)
Jan 19 00:14:56 Gunkkk gnome-session[1266]: ** (gnome-control-center:2685): WARNING **: Ignoring launcher landscape-client-settings (missing desktop file)

**Comment by jakeday** [comment]
@Gunkkk Are you saying the issue is resolved now after updating?

**Comment by Gunkkk** [comment]
Yes   I can use my wifi
However the suspending problem is still troubling.

**Comment by jakeday** [comment]
@Gunkkk You mean suspending when you hit the power button and it looks like it locks up?

**Comment by Gunkkk** [comment]
Yes 
 When it is in sleeping status upon i hit the power button or leave it a period of time that I have set ,the Typecover seems  cant be controlled and the screen is black  ，but the power is still.

**Comment by jakeday** [comment]
@Gunkkk That may be related to the type cover not re-attaching. Can you try the udev rule I added a note for at the bottom of the readme?

**Comment by Gunkkk** [comment]
### @jakeday  Well I have tried times and it just didn't work.Even more it will leads to many error such as the wifi problem and the touch of Type cover
_Here is the log ._

Jan 20 10:49:38 Gunkkk systemd[1]: Stopping udev Kernel Device Manager...
Jan 20 10:49:38 Gunkkk systemd[1]: Stopped udev Kernel Device Manager.
Jan 20 10:49:38 Gunkkk systemd[1]: Starting udev Kernel Device Manager...
Jan 20 10:49:38 Gunkkk systemd[1]: Started udev Kernel Device Manager.
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8428] manager: sleep requested (sleeping: no  enabled: yes)
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8429] manager: sleeping...
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8429] device (8C:0D:76:E8:64:83): state change: disconnected -> unmanaged (reason 'sleeping') [30 10 37]
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8431] manager: NetworkManager state is now ASLEEP
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8436] device (wlp1s0): state change: activated -> deactivating (reason 'sleeping') [100 110 37]
Jan 20 10:50:15 Gunkkk whoopsie[898]: [10:50:15] offline
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8571] device (wlp1s0): state change: deactivating -> disconnected (reason 'sleeping') [110 30 37]
Jan 20 10:50:15 Gunkkk avahi-daemon[759]: Withdrawing address record for fe80::f11d:d28a:75eb:253a on wlp1s0.
Jan 20 10:50:15 Gunkkk avahi-daemon[759]: Leaving mDNS multicast group on interface wlp1s0.IPv6 with address fe80::f11d:d28a:75eb:253a.
Jan 20 10:50:15 Gunkkk avahi-daemon[759]: Interface wlp1s0.IPv6 no longer relevant for mDNS.
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8909] dhcp4 (wlp1s0): canceled DHCP transaction, DHCP client pid 1137
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8909] dhcp4 (wlp1s0): state changed bound -> done
Jan 20 10:50:15 Gunkkk avahi-daemon[759]: Withdrawing address record for 192.168.1.118 on wlp1s0.
Jan 20 10:50:15 Gunkkk avahi-daemon[759]: Leaving mDNS multicast group on interface wlp1s0.IPv4 with address 192.168.1.118.
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.8924] dns-mgr: Removing DNS information from /sbin/resolvconf
Jan 20 10:50:15 Gunkkk avahi-daemon[759]: Interface wlp1s0.IPv4 no longer relevant for mDNS.
Jan 20 10:50:15 Gunkkk wpa_supplicant[1075]: wlp1s0: CTRL-EVENT-DISCONNECTED bssid=f4:83:cd:f9:3e:42 reason=3 locally_generated=1
Jan 20 10:50:15 Gunkkk kernel: [  592.313558] mwifiex_pcie 0000:01:00.0: info: successfully disconnected from f4:83:cd:f9:3e:42: reason code 3
Jan 20 10:50:15 Gunkkk whoopsie[898]: [10:50:15] Cannot reach: https://daisy.ubuntu.com
Jan 20 10:50:15 Gunkkk wpa_supplicant[1075]: wlp1s0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
Jan 20 10:50:15 Gunkkk dbus[741]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jan 20 10:50:15 Gunkkk systemd[1]: Starting Network Manager Script Dispatcher Service...
Jan 20 10:50:15 Gunkkk dbus[741]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jan 20 10:50:15 Gunkkk systemd[1]: Started Network Manager Script Dispatcher Service.
Jan 20 10:50:15 Gunkkk nm-dispatcher: req:1 'down' [wlp1s0]: new request (1 scripts)
Jan 20 10:50:15 Gunkkk nm-dispatcher: req:1 'down' [wlp1s0]: start running ordered scripts...
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <warn>  [1516416615.9378] sup-iface[0x25f3a20,wlp1s0]: connection disconnected (reason -3)
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.9379] device (wlp1s0): supplicant interface state: completed -> disconnected
Jan 20 10:50:15 Gunkkk NetworkManager[767]: <info>  [1516416615.9386] device (wlp1s0): state change: disconnected -> unmanaged (reason 'sleeping') [30 10 37]
Jan 20 10:50:15 Gunkkk whoopsie[898]: [10:50:15] Cannot reach: https://daisy.ubuntu.com
Jan 20 10:50:15 Gunkkk wpa_supplicant[1075]: nl80211: deinit ifname=wlp1s0 disabled_11b_rates=0
Jan 20 10:50:17 Gunkkk google-chrome.desktop[2006]: [2006:2044:0120/105017.396200:ERROR:connection_factory_impl.cc(381)] Failed to connect to MCS endpoint with error -106
Jan 20 10:50:17 Gunkkk systemd[1]: Reached target Sleep.
Jan 20 10:50:17 Gunkkk systemd[1]: Starting Suspend...
Jan 20 10:50:17 Gunkkk systemd[1]: Stopped Network Manager Wait Online.
Jan 20 10:50:17 Gunkkk systemd[1]: Stopping Network Manager...
Jan 20 10:50:17 Gunkkk NetworkManager[767]: <info>  [1516416617.5164] caught SIGTERM, shutting down normally.
Jan 20 10:50:17 Gunkkk NetworkManager[767]: <info>  [1516416617.5183] exiting (success)
Jan 20 10:50:17 Gunkkk systemd-sleep[2759]: Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory
Jan 20 10:50:17 Gunkkk systemd[1]: Stopped Network Manager.
Jan 20 10:50:17 Gunkkk systemd-sleep[2759]: rmmod: ERROR: Module intel_ipts is not currently loaded
Jan 20 10:50:17 Gunkkk gnome-session[948]: Gjs-Message: JS LOG: Removing a network device that was not added
Jan 20 10:50:17 Gunkkk gnome-session[1290]: Gjs-Message: JS LOG: Removing a network device that was not added
Jan 20 10:50:17 Gunkkk kernel: [  594.046255] mwifiex_pcie 0000:01:00.0: info: shutdown mwifiex...
Jan 20 10:50:17 Gunkkk kernel: [  594.046580] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 20 10:50:17 Gunkkk systemd[1]: Starting Load/Save RF Kill Switch Status...
Jan 20 10:50:17 Gunkkk systemd[1]: Started Load/Save RF Kill Switch Status.
Jan 20 10:50:17 Gunkkk systemd-sleep[2760]: /lib/systemd/system-sleep/wpasupplicant failed with error code 255.
Jan 20 10:50:17 Gunkkk systemd-sleep[2759]: Suspending system...
Jan 20 10:51:20 Gunkkk rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="799" x-info="http://www.rsyslog.com"] start
Jan 20 10:51:20 Gunkkk rsyslogd-2222: command 'KLogPermitNonKernelFacility' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.16.0 try http://www.rsyslog.com/e/2222 ]

**Comment by Gunkkk** [comment]
.@jakeday  Well, the probem seems solved atfer i  do the tips 5 instead of 6 (im not Ubuntu17.10)
The system can come into sleep while the screen cant be black? Is that normal

**Comment by jakeday** [comment]
@Gunkkk What do you mean tips 5 instead of 6?

**Comment by jakeday** [comment]
@Gunkkk  Can you give this another try with the latest builds I pushed? I re-compiled 4.15.1 and 4.14.17 with my updated wifi patches, so download the latest ones and give it a shot.

**Comment by jakeday** [comment]
Wifi issue is resolved, and the remaining issue is a result of #56
